### ISSUE TITLE
Two-phase Pseudo Label Densification for Self-training based Domain Adaptation

### ISSUE THREAD

**Issue by Lufei-github** [feipan664/IntraDA#11]
Sorry to bother you. Your team will release the code of the above paper?

**Comment by feipanir** [comment]
Hey thanks for your interests in our work on ECCV 2020. Our team recently is considering of journal extension so we are not ready to upload now. But we will try best to release as soon as possible.

**Comment by Jo-wang** [comment]
> 

Hi Fei, just wondering of the code for the above paper has been released already. I still cannot find any related code.

Thank you.
Jo
