### ISSUE TITLE
Could you update the entire training code of intraDA?

### ISSUE THREAD

**Issue by Sam-955** [feipan664/IntraDA#13]
Can you update the entire training code of intraDA? The training code here is the code of ADVENT.

**Comment by bryanbocao** [comment]
@Sam-955 The entire training has three stages as stated in the paper, where the first stage of inter-domain adaptation is the same as ADVENT while the intra-domain adaptation training code is the third stage:

Step 3. Conduct intra-domain adaptation by runing:
```
$ cd <root_dir>/intrada
$ python train.py --cfg ./intrada.yml
$ python train.py --cfg ./intrada.yml --tensorboard % using tensorboard
```
