### ISSUE TITLE
is there a batch size of 1 per gpu?

### ISSUE THREAD

**Issue by seominseok0429** [feipan664/IntraDA#2]
Your research has inspired me very much. So I'm trying to reproduce this experiment, is there a batch size of 1 per gpu?

**Comment by feipan664** [comment]
Yes, we use batch_size=1 during training process. More batches are allowed if the image size is smaller.

**Comment by seominseok0429** [comment]
If so, did all hyper-lamatenors keep the config in ADVENT?

**Comment by feipan664** [comment]
you are right, we use the same configuration as in AdvEnt.

**Comment by seominseok0429** [comment]
Thank you for your kind answer. Your research has inspired me very much. Thank you for your great research.
