### ISSUE TITLE
IntraDA trained from scratch or from InterDA params?

### ISSUE THREAD

**Issue by zhangyuygss** [feipan664/IntraDA#4]
Hey, how do you initialize the model in the intra-da stage, train from scratch, or resume from where the inter-da stopped?
It seems that resume from inter-da step is a  more reasonable way.
By the way, how does the quality of masks of easy samples influence the intra-da step? Will not-so-good masks lead to worse results?

**Comment by feipanir** [comment]
For GTA5->cityscapes experiment, we actually trained from scratch during intra-da stage. As we compare "training from scratch" and "resume from inter-da", there is not much difference in segmentation task. But it is possible to be different in other experiments. For the quality of masks of easy samples, it really affects the final results so we suggest you to get cleaner maps for easy sample.
