### ISSUE TITLE
How to implement from Synscapes/SYNTHIA to Cityscapes?

### ISSUE THREAD

**Issue by BinhuiXie** [feipan664/IntraDA#6]
Thanks for your great work, but I have a little confusion about loading Synscapes and SYNTHIA dataset. Could you please provide some suggestions?

BTW, in the first stage, can I directly use the provided evaluation models of ADVENT and AdaptSegNet?

**Comment by feipanir** [comment]
Yes, we actually borrow the results from ADVENT and AdaptSegNet at the first stage.
