### ISSUE TITLE
The initial parameters of the model for intra-domain adaptation

### ISSUE THREAD

**Issue by weiliuxm** [feipan664/IntraDA#8]
Hello, thank you for sharing your codes.

could you tell me the initial parameters of the model in step 3, please?
Are they loaded from DeepLab_resnet_pretrained_imagenet.pth or retrained by ADVENT?
Thank you in advance.

**Comment by feipanir** [comment]
Hi we tried both methods of loading from DeepLab_resnet_pretrained_imagenet.pth and also from ADVNET. In our experiments, Deeplab pretrained parameters gives slightly better performance.
