### ISSUE TITLE
About trained model of ADVENT

### ISSUE THREAD

**Issue by zhangchbin** [feipan664/IntraDA#9]
Hi, could you provide the trained model in STEP-1 (ADVENT) ?
We reproduce the first step using your code keeping the default setting, and we got the mIoU=40.9.
I believe many researchers have struggled in the same problem.
If you can provide the trained model of the first phase (ADVENT), we will be grateful.
Thanks.

**Comment by feipanir** [comment]
Sincerely sorry for late reply due to my schedule. You can send me an email so that I will share the trained ADVENT file to you. 

Best regards,

**Comment by zhangchbin** [comment]
> Sincerely sorry for late reply due to my schedule. You can send me an email so that I will share the trained ADVENT file to you.
> 
> Best regards,

Thanks for your reply~
